version: '2.4'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - cocusData:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=cocus"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
    ports:
      - "3333:3306"

volumes:
  cocusData:
